#ifndef PHOTONICS_PHOTONICS_H_ENUM_GEO_TYPE_ENUM_DEFINED
#define PHOTONICS_PHOTONICS_H_ENUM_GEO_TYPE_ENUM_DEFINED
typedef enum {
  SPHERICAL   = 1,
  CYLINDRICAL = 2,
  CUBIC       = 3  
} geo_type;
#endif /* PHOTONICS_PHOTONICS_H_ENUM_GEO_TYPE_ENUM_DEFINED */

#ifndef PHOTONICS_PHOTONICS_H_ENUM_PARITY_TYPE_ENUM_DEFINED
#define PHOTONICS_PHOTONICS_H_ENUM_PARITY_TYPE_ENUM_DEFINED
typedef enum {
  EVEN = 0,
  ODD = 1
} parity_type;
#endif /* PHOTONICS_PHOTONICS_H_ENUM_PARITY_TYPE_ENUM_DEFINED */

