# - Try to find CLHEP
# Once done this will define
#
#  CLHEP_FOUND - system has CLHEP
#  CLHEP_INCLUDE_DIR - the CLHEP include directory
#  CLHEP_LIBRARIES - The libraries needed to use CLHEP
#  CLHEP_DEFINITIONS - Compiler switches required for using CLHEP
#

MESSAGE(STATUS "    Looking for CLHEP")

FIND_PATH(CLHEP_INCLUDE_DIR NAMES CLHEP
  PATHS ${CLHEP_BASE_DIR}/include
  NO_DEFAULT_PATH
)

IF(NOT ${CLHEP_INCLUDE_DIR} MATCHES ".*NOTFOUND$")

  FIND_PATH(CLHEP_LIBRARY_DIR NAMES libCLHEP.so
    PATHS ${CLHEP_BASE_DIR}/lib
    NO_DEFAULT_PATH
    )
  IF(NOT ${CLHEP_LIBRARY_DIR} MATCHES ".*NOTFOUND$")

    IF(CLHEP_BASE_DIR AND CLHEP_INCLUDE_DIR AND CLHEP_LIBRARY_DIR)
      SET(CLHEP_FOUND TRUE)
    ENDIF(CLHEP_BASE_DIR AND CLHEP_INCLUDE_DIR AND CLHEP_LIBRARY_DIR)
    
    IF(CLHEP_FOUND)
      MESSAGE(STATUS "    + found at ${CLHEP_BASE_DIR}")
      INCLUDE_DIRECTORIES(${CLHEP_INCLUDE_DIR})
      LINK_DIRECTORIES(${CLHEP_LIBRARY_DIR})
      LINK_LIBRARIES("CLHEP")
    ENDIF(CLHEP_FOUND)
  ENDIF(NOT ${CLHEP_LIBRARY_DIR} MATCHES ".*NOTFOUND$")
ENDIF(NOT ${CLHEP_INCLUDE_DIR} MATCHES ".*NOTFOUND$")

IF (CLHEP_FOUND)
  MESSAGE(STATUS "    Looking for CLHEP -- found")
ELSE (CLHEP_FOUND)
  MESSAGE(STATUS "    Looking for CLHEP -- not found")
ENDIF (CLHEP_FOUND)
